name: PGTap Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  pg_tap_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml
      - name: Run Tests
        run: supabase test db